version: '3'

services:
  graphql:
    container_name: graphql-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - ./logs/npm:/root/.npm/_logs
      - ./logs/pm2:/root/.pm2/logs
    # restart: always
    ports:
      - 4000:4000
    network_mode: host